
version: "3.4"

services:
  app:
    build:
      context: .
    container_name: overtrack
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      SECRET_KEY_BASE: super-secret
      DATABASE_URL: postgres://overtrack:secret@database/overtrack
    volumes:
      - type: bind
        source: .
        target: /overtrack
  database:
    image: postgres
    container_name: overtrack-db
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./config/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: overtrack
      POSTGRES_DB: overtrack

volumes:
  database: {}