
version: "3.4"

services:
  app:
    build:
      context: .
    container_name: overtrack
    restart: always
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/ontrack
      - node_modules:/ontrack/node_modules
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      SECRET_KEY_BASE: super-secret
      DATABASE_URL: postgres://overtrack:secret@database/overtrack
  database:
    image: postgres
    container_name: overtrack-db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: overtrack
      POSTGRES_DB: overtrack

volumes:
  database: {}
  node_modules: