
version: "3.4"

services:
  database:
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
    environment:
  #    POSTGRES_HOST_AUTH_METHOD: md5
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: overtrack
      POSTGRES_DB: overtrack

  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@overtrack.com
      PGADMIN_DEFAULT_PASSWORD: overtrack
      GUNICORN_ACCESS_LOGFILE: '/dev/null'
    ports:
      - "5555:80"
    logging:
      driver: none
    restart: unless-stopped
    
  app:
    build:
      context: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      RAILS_ENV: production
      FORCE_SSL: false
      SECRET_KEY_BASE: super-secret
      DATABASE_URL: postgres://overtrack:secret@database/overtrack


volumes:
  database: {}