
version: "3.4"

services:
  database:
    image: postgres
    container_name: overtrack-db

  pgadmin:
    image: dpage/pgadmin4
    
  app:
    container_name: overtrack
    depends_on:
      - database
    